site_name: 'AI Racing League'
nav:
  - Home: index.md
  - About:
    - About at ARL: about.md
    - Business Plan: business-plan-2020.md
    - Contacts: contacts.md
  - Curriculum:
    - Learning Strategy: learning-strategy.md
    - Curriculum Overview: curriculum.md
    - Sample Six Week Course: six-week-curriculum.md
    - Computer Vision Labs:
      - Introduction: lesson-plans/computer-vision/index.md
      - Open Computer Vision: lesson-plans/computer-vision/open-cv.md
      - Face Filters: lesson-plans/computer-vision/face-filters.md
    - Jupyter Notebooks: lesson-plans/jupyter-notebooks/index.md
    - Car Data Analysis:
      - Introduction: lesson-plans/data-analysis/index.md
      - Intro Part 2: lesson-plans/data-analysis/01-intro.md
      - Listing Files: lesson-plans/data-analysis/02-listing-files.md
      - Viewing Images: lesson-plans/data-analysis/03-viewing-images.md
      - Viewing Catalog Files: lesson-plans/data-analysis/04-viewing-catalog-files.md
      - Catalog Statistics: lesson-plans/data-analysis/05-catalog-statistics.md
      - Cleaning Datasets: lesson-plans/data-analysis/06-cleaning-datasets.md
      - Data Distributions: data-analysis/06-data-distributions.md
    - Generative AI:
      - Generating Block Diagrams: lesson-plans/car-structure/index.md
    - Sample Quizzes:
      - GPU Commands: quizzes/gpu-commands.md
  - Setup:
    - Track Options: setup/track-options.md
    - Battery Options: setup/battery-options.md
    - MicroSD Options: setup/microSD-write-speed.md
    - Camera Testing: setup/camera-testing.md
    - GPU Options: setup/gpu-options.md
    - Car Checklist: admin/car-box-checklist/index.html
    - Building ARL Image: setup/building-arl-image.md
    - Calibrate: setup/calibrate.md
    - Setup Conda on Pi: setup/conda-pi-setup.md
    - PWM Setup: setup/pwm-board.md
    - Raspberry Pi Parts: setup/raspberry-pi-parts.md
    - Nano Docker: setup/nano-docker.md
    - Nano SD Image Checklist: setup/nano-sd-image-checklist.md
    - Software Installation Notes: setup/software-install-notes.md
    - Nano Upgrade: setup/nano-python-upgrade.md
    - Installation Tips: setup/installation-tips.md
    - Clone an SD Card: setup/clone-sd.md
    - Tools: admin/tools.md
  - GPU Server Setup:
    - NVIDIA Driver Installation: admin/nvidia-driver-install.md
    - GPU Shell Commands: admin/gpu-shell.md
    - Tensorflow GPU Software: admin/tensorflow-gpu-install.md
  - Team Administration:
    - Introduction: admin/01-intro.md
    - Custom Club Images: admin/02-sd-image.md
    - Purchasing Guide: admin/03-purchasing-guide.md
    - Cars Parts List: admin/car-parts-list.md
    - GPU Parts List: admin/gpu-parts.md
    - Car Box Checklist: admin/car-box-checklist.md
    - Joystick: admin/joystick.md
  - Training Logs:
     - MSP Car 1: training-logs/msp-car-1.md
     - MSP Car 2: training-logs/msp-car-2.md
     - Dan's Basement: training-logs/dans-basement.md
  - Misc:
    - Hackathon: hackathon.md
    - Demos: demos.md
    - Media: media.md
    - Command Line Tips: command-line-tips.md
    - Google Analytics: google-analytics.md
  - Presentations:
    - List of Presentations: presentations.md
    - Welcome: slides/Welcome-to-the-ARL.pptx
    - Command Reference Card: slides/Command-Reference-Card.pptx
    - Code Savvy Slides: slides/AI-Racing-League-Code-Savvy.pptx
    - Connecting PWM Cards: slides/Connecting-PWM-Cards.pptx
  - FAQs: faqs.md
  - Glossary: glossary.md
  - Resources: resources.md
repo_url: 'https://github.com/CoderDojoTC/ai-racing-league'

# Standard Stuff
repo_name: 'Link to GitHub'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/car-small.png
  favicon: img/favicon.png
  palette:
    primary: 'black'
    accent: 'blue'
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
extra:
  analytics:
    provider: google
    property: G-RL4MZ0MHZ4

