site_name: 'AI Racing League'
nav:
  - Home: index.md
  - About:
    - About at ARL: about.md
    - Business Plan: business-plan-2020.md
    - Presentations: presentations.md
    - Contacts: contacts.md
  - Curriculum:
    - Learning Strategy: learning-strategy.md
    - Curriculum: curriculum.md
    - Sample Six Week Course: six-week-curriculum.md
  - Setup:
    - Setup Conda on Pi: pi-setup.md
  - Hardware:
    - Cars Parts List: car-parts-list.md
    - GPU Parts List: gpu-parts.md
    - Car Box Checklist: car-box-checklist.md
    - Joystick: joystick.md
  - Misc:
    - Hackathon: hackathon.md
    - Demos: demos.md
    - Media: media.md
  - Presentations:
    - List of Presentations: presentations.md
    - Welcome: slides/Welcome-to-the-ARL.pptx
    - Command Reference Card: Command-Reference-Card.md
    - Code Savvy Slides: AI-Racing-League-Code-Savvy.pptx
  - FAQs: faqs.md
  - Glossary: glossary.md
  - Resources: resources.md
repo_url: 'https://github.com/CoderDojoTC/ai-racing-league'

# Standard Stuff
repo_name: 'Link to GitHub'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/car-small.png
  favicon: img/favicon.png
  palette:
    primary: 'black'
    accent: 'blue'
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite:
      linenums: true